$ a_peak = 0.784532 mm/ms^2 = 80.0000 g
$ t3 = 28.539319 ms,  delta_v = 17.912007 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_80p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_80p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
            5.707864            0.784532
           22.831455            0.784532
           28.539319            0.000000
