$ a_peak = 0.882599 mm/ms^2 = 90.0000 g
$ t3 = 25.368283 ms,  delta_v = 17.912007 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_90p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_90p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
            5.073657            0.882599
           20.294627            0.882599
           25.368283            0.000000
