$ a_peak = 0.294200 mm/ms^2 = 30.0000 g
$ t3 = 110.897394 ms,  delta_v = 26.100766 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_30p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_30p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
           22.179479            0.294200
           88.717915            0.294200
          110.897394            0.000000
