$ a_peak = 0.490333 mm/ms^2 = 50.0000 g
$ t3 = 45.662910 ms,  delta_v = 17.912007 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_50p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_50p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
            9.132582            0.490333
           36.530328            0.490333
           45.662910            0.000000
