$ a_peak = 0.588399 mm/ms^2 = 60.0000 g
$ t3 = 38.052425 ms,  delta_v = 17.912007 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_60p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_60p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
            7.610485            0.588399
           30.441940            0.588399
           38.052425            0.000000
