$ a_peak = 0.196133 mm/ms^2 = 20.0000 g
$ t3 = 166.346091 ms,  delta_v = 26.100766 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_20p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_20p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
           33.269218            0.196133
          133.076873            0.196133
          166.346091            0.000000
