$ a_peak = 0.980665 mm/ms^2 = 100.0000 g
$ t3 = 33.269218 ms,  delta_v = 26.100766 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_100p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_100p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
            6.653844            0.980665
           26.615375            0.980665
           33.269218            0.000000
