$ a_peak = 0.490333 mm/ms^2 = 50.0000 g
$ t3 = 66.538436 ms,  delta_v = 26.100766 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_50p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_50p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
           13.307687            0.490333
           53.230749            0.490333
           66.538436            0.000000
