$ a_peak = 0.980665 mm/ms^2 = 100.0000 g
$ t3 = 22.831455 ms,  delta_v = 17.912007 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_100p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_100p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
            4.566291            0.980665
           18.265164            0.980665
           22.831455            0.000000
