$ a_peak = 2.941995 mm/ms^2 = 300.0000 g
$ t3 = 11.089739 ms,  delta_v = 26.100766 mm/ms
$ X = time [ms],  Y = acceleration [mm/ms^2]
*DEFINE_CURVE
$HMNAME CURVES         2curve_acceleration_SLED_300p000g
$HWCOLOR CURVES         2      24
$HMCURVE     1    0 curve_acceleration_SLED_300p000g
$     LCID      SIDR       SFA       SFO      OFFA      OFFO    DATTYP     LCINT
         2                 1.0       1.0
$                  X                   Y
            0.000000            0.000000
            2.217948            2.941995
            8.871792            2.941995
           11.089739            0.000000
